services:
  # ----------------------------------------
  # REVERSE PROXY: Caddy
  # ----------------------------------------
  caddy:
    image: caddy:latest
    container_name: caddy
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./caddy/Caddyfile:/etc/caddy/Caddyfile
      - caddy_data:/data
      - caddy_config:/config

  # ----------------------------------------
  # MOODLE med MariaDB
  # ----------------------------------------
  moodle-db:
    image: mariadb:10.6
    container_name: moodle-db
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: moodle_db
      MYSQL_USER: teknikkeren
      MYSQL_PASSWORD: "Fn+Qteknikkeren"
      MYSQL_ROOT_PASSWORD: "Fn+Qteknikkeren"
    volumes:
      - moodle_db_data:/var/lib/mysql

  moodle-app:
    image: bitnami/moodle:latest
    container_name: moodle-app
    restart: unless-stopped
    environment:
      MOODLE_DATABASE_HOST: moodle-db
      MOODLE_DATABASE_NAME: moodle_db
      MOODLE_DATABASE_USER: teknikkeren
      MOODLE_DATABASE_PASSWORD: "Fn+Qteknikkeren"
      MOODLE_USERNAME: teknikkeren
      MOODLE_PASSWORD: "Fn+Qteknikkeren"
      # Bitnami-moodle lytter standard på 8080/8443:
      # Vil du TVINGE port 80/443 i containeren i stedet?
      # MOODLE_HTTP_PORT_NUMBER: 80
      # MOODLE_HTTPS_PORT_NUMBER: 443

      # Valgfritt: For enkel testing. Ikke sett "yes" i produksjon.
      ALLOW_EMPTY_PASSWORD: "yes"
    volumes:
      - moodle_data:/bitnami/moodle
    depends_on:
      - moodle-db

  # ----------------------------------------
  # OPENPROJECT med PostgreSQL
  # ----------------------------------------
  openproject-db:
    image: postgres:14
    container_name: openproject-db
    restart: unless-stopped
    environment:
      POSTGRES_DB: openproject_db
      POSTGRES_USER: teknikkeren
      POSTGRES_PASSWORD: "Fn+Qteknikkeren"
    volumes:
      - openproject_db_data:/var/lib/postgresql/data

  openproject-app:
    image: openproject/community:12
    container_name: openproject-app
    restart: unless-stopped
    environment:
      DATABASE_URL: "postgresql://teknikkeren:Fn+Qteknikkeren@openproject-db/openproject_db"
      # Evt. mer konfig (f.eks. SMTP).
    depends_on:
      - openproject-db
    # Lytter mest sannsynlig på port 80 i containeren.
    # Hvis det viser seg å være 3000, oppdater Caddyfile.

# ----------------------------------------
# DEFINERTE VOLUMER
# ----------------------------------------
volumes:
  moodle_db_data:
  moodle_data:
  openproject_db_data:
  caddy_data:
  caddy_config:
